# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - california-house-price-predict

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://californiahousingprice.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_f40a1ac366f0452c889a8b42972c8fdd }}
        password: ${{ secrets.AzureAppService_ContainerPassword_ec5067c65d324bd5ac1276b96bb266a9 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: californiahousingprice.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_f40a1ac366f0452c889a8b42972c8fdd }}/housepridiction:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'california-house-price-predict'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_81b9cbe94f93407ea4be8afc565812ff }}
        images: 'californiahousingprice.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_f40a1ac366f0452c889a8b42972c8fdd }}/housepridiction:${{ github.sha }}'